package other;

import java.util.Arrays;
import java.util.BitSet;

import gnu.trove.list.array.TIntArrayList;
import gnu.trove.list.array.TLongArrayList;
import gnu.trove.set.hash.TIntHashSet;
import main.Status;
import main.collections.FastTIntArrayList;
import other.context.Context;
import other.state.State;
import other.state.owned.Owned;
import other.state.track.OnTrackIndices;
import other.trial.Trial;

/**
 * Undo Data necessary to be able to undo a move.
 *
 * <p>Abstract snapshot of a Context. The 21 fields present for (effectively)
 * every game live here and are read straight off the Context. The 5 optional
 * reference fields some games use (pendingValues, remainingDominoes, visited,
 * sitesToRemove, onTrackIndices) are added by per-game subclasses generated by
 * UndoDataGenerator; games that do not use a field inherit the safe-empty stub
 * getters below.
 *
 * <p>Read-only after construction (Trial copies the endData list by reference),
 * so there is no copy()/resetStateTo()/initialise().
 *
 * @author Eric.Piette (original), specialization pipeline (this rewrite)
 */
public abstract class UndoData
{
	// Shared safe-empty sentinels returned by the base stubs. UndoData snapshots
	// are never mutated after construction, so sharing one empty instance is safe.
	private static final TIntHashSet       EMPTY_PENDING  = new TIntHashSet();
	private static final FastTIntArrayList EMPTY_DOMINOES = new FastTIntArrayList();
	private static final BitSet            EMPTY_VISITED  = new BitSet();
	private static final TIntArrayList     EMPTY_SITES    = new TIntArrayList();

	private final double[] ranking;
	private final Status status;
	private final TIntArrayList winners;
	private final TIntArrayList losers;
	private final int active;
	private final int[] scores;
	private final double[] payoffs;
	private final int numLossesDecided;
	private final int numWinsDecided;
	private final int[] phases;
	private final int counter;
	private final TLongArrayList previousStateWithinATurn;
	private final TLongArrayList previousState;
	private final int prev;
	private final int mover;
	private final int next;
	private final int numTurn;
	private final int numTurnSamePlayer;
	private final int numConsecutivePasses;
	private final Owned owned;
	private final int isDecided;

	/**
	 * @param context The context being snapshotted.
	 * @param active  The active-players bitmask (held privately on Context, no getter).
	 * @param phases  The per-player phase array (computed at the call site).
	 */
	protected UndoData(final Context context, final int active, final int[] phases)
	{
		final State state = context.state();
		final Trial trial = context.trial();

		final double[] r = trial.ranking();
		this.ranking = Arrays.copyOf(r, r.length);
		this.status = (trial.status() == null) ? null : new Status(trial.status());
		this.winners = new TIntArrayList(context.winners());
		this.losers = new TIntArrayList(context.losers());
		this.active = active;
		final int[] sc = context.scores();
		this.scores = (sc == null) ? null : Arrays.copyOf(sc, sc.length);
		final double[] pf = context.payoffs();
		this.payoffs = (pf == null) ? null : Arrays.copyOf(pf, pf.length);
		this.numLossesDecided = context.numLossesDecided();
		this.numWinsDecided = context.numWinsDecided();
		this.phases = (phases == null) ? null : Arrays.copyOf(phases, phases.length);
		this.counter = state.counter();
		this.previousStateWithinATurn = new TLongArrayList(trial.previousStateWithinATurn());
		this.previousState = new TLongArrayList(trial.previousState());
		this.prev = state.prev();
		this.mover = state.mover();
		this.next = state.next();
		this.numTurn = state.numTurn();
		this.numTurnSamePlayer = state.numTurnSamePlayer();
		this.numConsecutivePasses = state.numConsecutivesPasses();
		this.owned = (state.owned() == null) ? null : state.owned().copy();
		this.isDecided = state.isDecided();
	}

	//----------------------- always-present getters --------------------------

	public double[] ranking() { return ranking; }
	public Status status() { return status; }
	public TIntArrayList winners() { return winners; }
	public TIntArrayList losers() { return losers; }
	public int active() { return active; }
	public int[] scores() { return scores; }
	public double[] payoffs() { return payoffs; }
	public int numLossesDecided() { return numLossesDecided; }
	public int numWinsDecided() { return numWinsDecided; }
	public int[] phases() { return phases; }
	public int counter() { return counter; }
	public TLongArrayList previousStateWithinATurn() { return previousStateWithinATurn; }
	public TLongArrayList previousState() { return previousState; }
	public int prev() { return prev; }
	public int mover() { return mover; }
	public int next() { return next; }
	public int numTurn() { return numTurn; }
	public int numTurnSamePlayer() { return numTurnSamePlayer; }
	public int numConsecutivePasses() { return numConsecutivePasses; }
	public Owned owned() { return owned; }
	public int isDecided() { return isDecided; }

	//----------------------- prunable-field stubs ----------------------------
	// Overridden only by subclasses of games that carry the field. Defaults
	// match what specialized State returns for an absent field.

	public TIntHashSet pendingValues() { return EMPTY_PENDING; }
	public FastTIntArrayList remainingDominoes() { return EMPTY_DOMINOES; }
	public BitSet visited() { return EMPTY_VISITED; }
	public TIntArrayList sitesToRemove() { return EMPTY_SITES; }
	public OnTrackIndices onTrackIndices() { return null; }
}